const express = require("express");
const router = express.Router();
const { portoController } = require("./../controller/addPortofolio");
const upload = require("../middlewares/upload");
// router.post("/", PekerjaController.insert);
router.post("/:id", upload.single("photo"), portoController.insert);
router.put("/:id", upload.single("photo"), portoController.update);
router.get("/:id", portoController.getAllPorto);
router.delete("/:id", portoController.delete);
// router.put("/:id", experiencesControl.update);
// router.get("/detail/:id", experiencesControl.detailWork);
// router.get("/", experiencesControl.getAllWork);
module.exports = router;
